openapi: 3.0.0
info:
  title: Comment API
  version: 1.0.0
paths:
  /comments:
    get:
      summary: Get all comments
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

  /comments/{id}:
    get:
      summary: Get a comment by ID
      parameters:
        - name: id
          in: path
          description: ID of the comment to get
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
    put:
      summary: Update a comment by ID
      parameters:
        - name: id
          in: path
          description: ID of the comment to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
    delete:
      summary: Delete a comment by ID
      parameters:
        - name: id
          in: path
          description: ID of the comment to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        content:
          type: string
        dateCreated:
          type: string
          format: date-time