openapi: 3.0.0
info:
  title: Comment API
  version: 1.0.0
paths:
  /comments:
    get:
      summary: Get all comments
      responses:
        '200':
          description: A list of comments
    post:
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                content:
                  type: string
      responses:
        '201':
          description: Comment created successfully
    /{id}:
      get:
        summary: Get a specific comment
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '200':
            description: A specific comment
      put:
        summary: Update a specific comment
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                  content:
                    type: string
        responses:
          '200':
            description: Comment updated successfully
      delete:
        summary: Delete a specific comment
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
        responses:
          '204':
            description: Comment deleted successfully