openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
paths:
  /friends:
    get:
      summary: Get all friends
      responses:
        '200':
          description: OK
    post:
      summary: Add a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
      responses:
        '201':
          description: Created
    put:
      summary: Update a friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content