openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
paths:
  /friend:
    get:
      summary: Get all friends
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
    post:
      summary: Add a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
  /friend/{userId}:
    get:
      summary: Get friend by userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
    put:
      summary: Update an existing friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
    delete:
      summary: Delete a friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Friend deleted successfully
components:
  schemas:
    Friend:
      type: object
      properties:
        userId:
          type: integer
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date-time