openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
paths:
  /friend:
    get:
      summary: Get all friends
      responses:
        '200':
          description: Successful operation
    post:
      summary: Add a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend created successfully
  /friend/{userId}:
    get:
      summary: Get friend by userId
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the friend to get
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
        '404':
          description: Friend not found
    put:
      summary: Update an existing friend
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the friend to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend updated successfully
        '404':
          description: Friend not found
    delete:
      summary: Delete a friend
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the friend to delete
          schema:
            type: integer
      responses:
        '200':
          description: Friend deleted successfully
components:
  schemas:
    Friend:
      type: object
      properties:
        userId:
          type: integer
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date