openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
paths:
  /friends:
    get:
      summary: Get all friends
      responses:
        '200':
          description: A list of friends
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
    post:
      summary: Add a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend added successfully
  /friends/{userId}:
    get:
      summary: Get a friend by user ID
      parameters:
        - name: userId
          in: path
          description: ID of the friend to get
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single friend
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
    put:
      summary: Update a friend
      parameters:
        - name: userId
          in: path
          description: ID of the friend to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Friend'
      responses:
        '200':
          description: Friend updated successfully
    delete:
      summary: Delete a friend
      parameters:
        - name: userId
          in: path
          description: ID of the friend to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Friend deleted successfully
components:
  schemas:
    Friend:
      type: object
      properties:
        userId:
          type: integer
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date-time