openapi: 3.0.0
info:
  title: Friend API
  version: 1.0.0
paths:
  /friends:
    get:
      summary: Get all friends
      responses:
        '200':
          description: Successful operation
    post:
      summary: Add a new friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
      responses:
        '200':
          description: Successful operation
  /friends/{userId}:
    get:
      summary: Get friend by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the friend to get
      responses:
        '200':
          description: Successful operation
    put:
      summary: Update an existing friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the friend to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
      responses:
        '200':
          description: Successful operation
    delete:
      summary: Delete a friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the friend to delete
      responses:
        '200':
          description: Successful operation