openapi: 3.0.0
info:
  title: Obj API
  version: 1.0.0
paths:
  /obj:
    get:
      summary: Get all Obj entities
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Obj'
    post:
      summary: Create a new Obj entity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obj'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obj'
  /obj/{id}:
    get:
      summary: Get a specific Obj entity by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the Obj entity to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obj'
    put:
      summary: Update a specific Obj entity by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the Obj entity to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obj'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obj'
    delete:
      summary: Delete a specific Obj entity by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the Obj entity to delete
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
components:
  schemas:
    Obj:
      type: object
      properties:
        mId:
          type: integer
        mUserId:
          type: integer
        mContent:
          type: string
        mCaso:
          type: string
        utente:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        mUserId:
          type: integer
        mIsRepost:
          type: boolean
        mDateCreated:
          type: string
        amici:
          $ref: '#/components/schemas/Friend'
    Friend:
      type: object
      properties:
        mUserId:
          type: integer
        mIsRepost:
          type: boolean
        mDateCreated:
          type: string