openapi: 3.0.0
info:
  title: Obj API
  version: 1.0.0
paths:
  /obj:
    get:
      summary: Get all Obj
      responses:
        '200':
          description: OK
    post:
      summary: Create a new Obj
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obj'
      responses:
        '200':
          description: OK
    /{id}:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Obj ID
      get:
        summary: Get Obj by ID
        responses:
          '200':
            description: OK
          '404':
            description: Obj not found
      put:
        summary: Update Obj
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Obj'
        responses:
          '200':
            description: OK
          '404':
            description: Obj not found
      delete:
        summary: Delete Obj
        responses:
          '200':
            description: OK
          '404':
            description: Obj not found
components:
  schemas:
    Obj:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        caso:
          type: string
        utente:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        user_id:
          type: integer
        is_repost:
          type: boolean
        date_created:
          type: string
        amici:
          $ref: '#/components/schemas/Friend'
    Friend:
      type: object
      properties:
        user_id:
          type: integer
        is_repost:
          type: boolean
        date_created:
          type: string