openapi: 3.0.0
info:
  title: Obj API
  version: 1.0.0
paths:
  /obj:
    get:
      summary: Get all Obj
      responses:
        '200':
          description: Successful operation
    post:
      summary: Create a new Obj
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obj'
      responses:
        '200':
          description: Successful operation
  /obj/{objId}:
    get:
      summary: Get Obj by ID
      parameters:
        - name: objId
          in: path
          description: ID of the Obj to get
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Obj not found
    put:
      summary: Update an existing Obj
      parameters:
        - name: objId
          in: path
          description: ID of the Obj to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Obj'
      responses:
        '200':
          description: Successful operation
        '404':
          description: Obj not found
    delete:
      summary: Delete an Obj
      parameters:
        - name: objId
          in: path
          description: ID of the Obj to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Obj not found
components:
  schemas:
    Obj:
      type: object
      properties:
        objId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        content:
          type: string
        caso:
          type: string
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date
        friend:
          $ref: '#/components/schemas/Friend'
    Friend:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date