openapi: 3.0.0
info:
  title: Obj API
  version: 1.0.0
paths:
  /obj:
    get:
      summary: Get all Obj entities
      responses:
        '200':
          description: Successful operation
    post:
      summary: Create a new Obj entity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                content:
                  type: string
                caso:
                  type: string
      responses:
        '200':
          description: Successful operation
  /obj/{id}:
    get:
      summary: Get a specific Obj entity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
    put:
      summary: Update a specific Obj entity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                content:
                  type: string
                caso:
                  type: string
      responses:
        '200':
          description: Successful operation
    delete:
      summary: Delete a specific Obj entity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation