openapi: 3.0.0
info:
  title: Obj API
  version: 1.0.0
paths:
  /obj:
    get:
      summary: Get all Obj entities
      responses:
        '200':
          description: OK
    post:
      summary: Create a new Obj entity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mUserId:
                  type: integer
                mContent:
                  type: string
                mCaso:
                  type: string
      responses:
        '200':
          description: OK
  /obj/{id}:
    get:
      summary: Get a specific Obj entity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
    put:
      summary: Update a specific Obj entity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mUserId:
                  type: integer
                mContent:
                  type: string
                mCaso:
                  type: string
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a specific Obj entity
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK