```yaml
openapi: 3.0.0
info:
  title: Poll API
  version: 1.0.0
paths:
  /poll:
    get:
      summary: Get all polls
      responses:
        '200':
          description: Successful operation
    post:
      summary: Create a new poll
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        '200':
          description: Successful operation
  /poll/{id}:
    get:
      summary: Get a specific poll
      parameters:
        - name: id
          in: path
          description: ID of the poll to get
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Poll not found
    put:
      summary: Update a poll
      parameters:
        - name: id
          in: path
          description: ID of the poll to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
      responses:
        '200':
          description: Successful operation
        '404':
          description: Poll not found
    delete:
      summary: Delete a poll
      parameters:
        - name: id
          in: path
          description: ID of the poll to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Poll not found
components:
  schemas:
    Poll:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        question:
          type: string
        dateCreated:
          type: string
          format: date-time
        obj:
          $ref: '#/components/schemas/Obj'
        commento:
          $ref: '#/components/schemas/Comment'
    Obj:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        content:
          type: string
        caso:
          type: string
        utente:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date-time
        amici:
          $ref: '#/components/schemas/Friend'
    Friend:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        isRepost:
          type: boolean
        dateCreated:
          type: string
          format: date-time
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        content:
          type: string
        dateCreated:
          type: string
          format: date-time
```