openapi: 3.0.0
info:
  title: User Feed API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful operation
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
                friend:
                  type: object
                  properties:
                    friendId:
                      type: integer
      responses:
        '200':
          description: User created successfully
  /users/{userId}:
    get:
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
    put:
      summary: Update user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isRepost:
                  type: boolean
                dateCreated:
                  type: string
                  format: date
                friend:
                  type: object
                  properties:
                    friendId:
                      type: integer
      responses:
        '200':
          description: User updated successfully
    delete:
      summary: Delete user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully